//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetFy
{
    using System;
    using System.Collections.Generic;
    
    public partial class animales
    {
        public int idAnimal { get; set; }
        public string nombreAnimal { get; set; }
        public string caracteristicas { get; set; }
        public Nullable<bool> generoAnimal { get; set; }
        public Nullable<System.DateTime> fechaAnimal { get; set; }
        public byte[] fotoAnimal { get; set; }
        public Nullable<int> idRaza { get; set; }
        public Nullable<int> idTipo { get; set; }
        public Nullable<int> idHistorial { get; set; }
    
        public virtual historial historial { get; set; }
        public virtual razas razas { get; set; }
        public virtual tipos tipos { get; set; }
    }
}
