//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetFy
{
    using System;
    using System.Collections.Generic;
    
    public partial class donaciones
    {
        public int idDonacion { get; set; }
        public string nombreDonacion { get; set; }
        public Nullable<int> cantidadDonacion { get; set; }
    }
}
