//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetFy
{
    using System;
    using System.Collections.Generic;
    
    public partial class personal
    {
        public int idPersonal { get; set; }
        public string nombrePersonal { get; set; }
        public string direccionPersonal { get; set; }
        public string numeroPersonal { get; set; }
        public byte[] fotoPersonal { get; set; }
    }
}
