//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetFy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetfyDBEntities : DbContext
    {
        public PetfyDBEntities()
            : base("name=PetfyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<adoptantes> adoptantes { get; set; }
        public DbSet<animales> animales { get; set; }
        public DbSet<donaciones> donaciones { get; set; }
        public DbSet<historial> historial { get; set; }
        public DbSet<personal> personal { get; set; }
        public DbSet<productos> productos { get; set; }
        public DbSet<rangos> rangos { get; set; }
        public DbSet<razas> razas { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tipos> tipos { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
    }
}
