//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetFy
{
    using System;
    using System.Collections.Generic;
    
    public partial class razas
    {
        public razas()
        {
            this.animales = new HashSet<animales>();
        }
    
        public int idRaza { get; set; }
        public string nombreRaza { get; set; }
    
        public virtual ICollection<animales> animales { get; set; }
    }
}
